version: "3"

volumes:
  data:

networks:
  traefik-hub: {}
  traefik-networks:
    external: true

services:
  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v1.0.0
    pull_policy: always
    container_name: hub-agent
    restart: "on-failure"
    command:
      - run
      - --hub.token=63c13b92-1c10-4e30-bce1-7737ca749d57
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-hub
    depends_on:
      - traefik

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      # Enable Hub communication (open the port 9900 and 9901 by default)
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    networks:
      - traefik-hub

  app:
    build:
      context: .
      dockerfile: Dockerfile.app

    expose:
      - 8000
    ports:
      - 8000:8000
      - "8443:8000"

    restart: unless-stopped
    volumes:
      - data:/app/data
    networks:
      - traefik-hub
